[package]
name = "sgo"
version = "0.1.14"
edition = "2018"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
# clap = "4"  # 解析命令行参数
#clap = { version = "4" }  # 解析命令行参数
clap = "4.1" 
mime_guess = "2.0"