name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu, x86_64-apple-darwin]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: helix-editor/rust-toolchain@v1
      with:
        profile: minimal
    # - name: Set up Rust
    #   uses: rust-lang/setup-rust@v2
    #   with:
    #     rust-version: stable

    - name: Install cross
      run: cargo install cross

    - name: Build with cross
      run: cross build --target ${{ matrix.platform }} --release

    # - name: Upload binaries
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: ${{ matrix.platform }}-binary
    #     path: target/${{ matrix.platform }}/release/your_project_name
