name: CI Pipeline

# Steps:
# 1. Run ci.yml for every push to the main branch
# 2. Run tag.yml for every completed run of the CI Pipeline
# 3. Run cd.yml for every tag-creation-success event

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [1.74.0, stable, beta, nightly]
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
     
        - name: Run dtolnay/rust-toolchain${{contains(matrix.rust, ' ') && ' for ' || '@'}}${{matrix.rust}}
          uses: dtolnay/rust-toolchain@stable
          with:
            toolchain: ${{ matrix.rust }}

        - name: Install cross
          run: cargo install cross

        - name: Build with cross
          run: cargo build --release
