name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [1.69.0, stable, beta, nightly]
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
     
        - name: Run dtolnay/rust-toolchain${{contains(matrix.rust, ' ') && ' for ' || '@'}}${{matrix.rust}}
          uses: dtolnay/rust-toolchain@stable
          with:
            toolchain: ${{ matrix.rust }}

        - name: Install cross
          run: cargo install cross

        - name: Build with cross
          run: cargo build --release
